config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :messages, only: [:new, :create] do
    collection do
      get 'success'
    end
  end
  resources :music, only: [:index]
  # resources :shows, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :shows, only: [:index]
  resources :merch, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :contact_name
  validates_presence_of :contact_email
  validates_presence_of :message_body
  validates_presence_of :message_subject
end

app/models/show.rb
class Show < ApplicationRecord
  validates_presence_of :venue
  validates_presence_of :show_time
  validates_presence_of :show_date

  scope :upcoming, -> { where("show_date >= ?", Date.yesterday) }
  scope :past, -> { where("show_date <= ?", Date.yesterday) }

  def current?
    created_at >= Date.yesterday
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/merch_controller.rb
class MerchController < ApplicationController
  def index

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.find_or_create_by(contact_email: message_params[:contact_email])
    if @message.update(message_params)
      redirect_to success_messages_path
    else
      flash[:errors] = @message.errors.full_messages
      render :new
    end
  end

  def success

  end

  private
  def message_params
    params.require(:message).permit(:contact_name, :contact_email, :message_body, :message_subject, :contact_phone)
  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def index

  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  protect_from_forgery prepend: true # Look into deleting after we add user auth.
  before_action :get_show, only: [:edit, :update, :destroy]

  def index
    @upcoming = Show.upcoming.order(:show_date)
    @past = Show.past.order(show_date: :desc)
  end

  def new
    @show = Show.new
  end

  def create
    @show = Show.new(show_params)
    if @show.save
      redirect_to shows_path
    else
      flash[:errors] = @show.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def update
    if @show.update(show_params)
      redirect_to shows_path
    else
      flash[:errors] = @show.errors.full_messages
      render :edit
    end
  end

  def destroy
    @show.destroy
    redirect_to shows_path
  end

  private
  def show_params
    params.require(:show).permit(:venue, :presale_link, :supporting_acts, :show_time, :show_date)
  end

  def get_show
    @show=Show.find(params[:id])
  end
end

app/views/home/index.html.haml
.white.center-text
  =image_tag('Stilted_Demisefest.jpg', class: 'image')
  %br
  %br
  .container
    %p.black Stilted.  A three-piece rock and roll band from Fort Collins, Colorado.  Playing original music that runs the gauntlet from indie rock to (heavy) alternative, Stilted was once described as sounding like “the bastard love child of Nirvana and the Talking Heads”.  Cody delivers masterful lyrics with blazing guitar riffs, while Thom lays down thumping, rhythmic bass lines over KJ’s powerful drum beats.
  .btn-group.d-none.d-lg-block
    =link_to 'Shows', shows_path, class: 'btn btn-dark'
    =link_to 'Music', music_index_path, class: 'btn btn-dark'
    -# =link_to 'Merch', merch_index_path, class: 'btn btn-dark'
    =link_to 'Contact', new_message_path, class: 'btn btn-dark'
  %br

app/views/layouts/_footer.html.haml
%ul.white.center-text
  %li Cody Hitchcock - Guitar/Vocals
  %li Thom Miller - Bass
  %li KJ Osenenko - Drums

app/views/layouts/_navigation.html.haml
.navbar.navbar-expand-lg.nav-background
  .container-fluid
    %h1= link_to 'STILTED', root_path, class: 'logo'
    .d-none.d-lg-block
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-link
          = link_to 'Listen Now', music_index_path, class: 'btn btn-dark'
        %li.nav-link
          = link_to 'Upcoming Shows', shows_path, class: 'btn btn-dark'
        -# %li.nav-link
          -# = link_to 'Merch', merch_index_path, class: 'btn btn-dark'
        %li.nav-link
          = link_to 'Booking / Contact', new_message_path, class: 'btn btn-dark'
    .d-lg-none
      .btn-group
        = link_to 'Shows', shows_path, class: 'btn btn-dark'
        = link_to 'Music', music_index_path, class: 'btn btn-dark'
        -# = link_to 'Merch', merch_index_path, class: 'btn btn-dark'
        = link_to 'Contact', new_message_path, class: 'btn btn-dark'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Stilted
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{href: "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3", crossorigin: "anonymous"}
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = favicon_link_tag 'stilted_favicon.png'
  %body
    =render partial: "layouts/navigation"
    %br.d-none.d-lg-block
    #container-div.container.d-none.d-lg-block
      = yield
    #mobile-container.d-lg-none
      = yield
    %br
    =render partial: "layouts/footer"

app/views/merch/index.html.haml
.black.center-text
  %h1.monoton STILTED SHOP
  %p Coming Soon...

app/views/messages/new.html.haml
.black
  %h1.center-text CONTACT US
  -if flash[:errors]
    %ul.alert.alert-warning
      -flash[:errors].each do |e|
        %li=e
  .container
    =form_for @message, data: { turbo: false } do |f|
      .row.my-2
        .col-md-6
          =f.label :contact_name, 'Name'
          =f.text_field :contact_name
        .col-md-6
          =f.label :contact_email, 'Email'
          =f.text_field :contact_email
      .row.my-2
        .col-md-6
          =f.label :message_subject, 'Subject'
          =f.text_field :message_subject
        .col-md-6
          =f.label :contact_phone, 'Phone'
          =f.text_field :contact_phone
      .my-2
        =f.label :message_body, "message"
        =f.text_area :message_body
      .col-md-1
        =f.submit 'Send', class: 'btn btn-dark'
%br

app/views/messages/success.html.haml
.black
  %h3.center-text Thank you, your message has been delivered.
  .center-text
    =link_to 'Return Home', root_path, class: 'btn btn-dark'

app/views/music/index.html.haml
.black.center-text
  %h1.monoton LATEST RELEASES
  .music-container
    %iframe.track.d-none.d-lg-block{src:"https://bandcamp.com/EmbeddedPlayer/track=1856865821/size=large/bgcol=333333/linkcol=e32c14/tracklist=false/artwork=small/transparent=true/"}
      %a{href: "https://stilted.bandcamp.com/track/were-gonna-make-it"}
    %iframe.track.d-none.d-lg-block{src:"https://bandcamp.com/EmbeddedPlayer/track=2459908476/size=large/bgcol=333333/linkcol=e32c14/tracklist=false/artwork=small/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/track/brightly-lit-room"}
    %iframe.album.d-none.d-lg-block{src:"https://bandcamp.com/EmbeddedPlayer/album=775819202/size=large/bgcol=333333/linkcol=e32c14/artwork=small/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/album/the-big-picture-aside"}
    %iframe.track-mobile.d-lg-none{src:"https://bandcamp.com/EmbeddedPlayer/track=1856865821/size=small/bgcol=333333/linkcol=e32c14/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/track/were-gonna-make-it"}
    %iframe.track-mobile.d-lg-none{src:"https://bandcamp.com/EmbeddedPlayer/track=2459908476/size=small/bgcol=333333/linkcol=e32c14/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/track/brightly-lit-room"}
    %iframe.track-mobile.d-lg-none{src:"https://bandcamp.com/EmbeddedPlayer/album=775819202/size=small/bgcol=333333/linkcol=e32c14/track=3946968099/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/album/the-big-picture-aside"}
    %iframe.track-mobile.d-lg-none{src:"https://bandcamp.com/EmbeddedPlayer/album=775819202/size=small/bgcol=333333/linkcol=e32c14/track=3898717670/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/album/the-big-picture-aside"}
    %iframe.track-mobile.d-lg-none{src:"https://bandcamp.com/EmbeddedPlayer/album=775819202/size=small/bgcol=333333/linkcol=e32c14/track=903824012/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/album/the-big-picture-aside"}
    %iframe.track-mobile.d-lg-none{src:"https://bandcamp.com/EmbeddedPlayer/album=775819202/size=small/bgcol=333333/linkcol=e32c14/track=1810433489/transparent=true/"}
      %a{href:"https://stilted.bandcamp.com/album/the-big-picture-aside"}

app/views/shows/_form.html.haml
.black
  %h1.center-text NEW SHOW
  -if flash[:errors]
    %ul.alert.alert-warning
      -flash[:errors].each do |e|
        %li=e
  =form_for @show, data: { turbo: false }do |f|
    .row.my-1
      .col-md-8
        =f.label :venue, 'Venue'
        =f.text_field :venue
      .col-md-4
        =f.label :show_date, 'Show Date'
        =f.date_field :show_date
    .row.my-1
      .col-md-8
        =f.label :presale_link, 'Presale Link'
        =f.text_field :presale_link
      .col-md-4
        =f.label :show_time, 'Show Time'
        =f.text_field :show_time
    .row.my-1
      .col-md-12
        =f.label :supporting_acts, 'Supporting Acts'
        =f.text_field :supporting_acts
    .row.my-2
      .col-md-1
        =f.submit 'Save', class: 'btn btn-success'
      .col-md-1
        =link_to 'Cancel', shows_path, class: 'btn btn-dark'
      -if @show.id 
        .col-md-1
          =button_to 'Delete', @show, class: 'btn btn-warning', method: :delete, onclick: "return confirmDestroy('Are you sure want delete this show?')"
:javascript
  function confirmDestroy(message) {
    if (!confirm(message)) {
      return false
    }
  }

app/views/shows/_list.html.haml
-shows.each do |show|
  .card
    .row
      -# .col-md-3
        -# =image_tag('surfside_12_8_22.jpg', class: 'show_image')
      .col-md-12
        .card-body
          %h3=show.venue
          -if show.supporting_acts.present?
            %h5 
              With
              =show.supporting_acts
          %h5
            =show.show_date.strftime('%m/%d/%Y')
            =show.show_time
          -if show.current? && show.presale_link.present?
            =link_to 'More info', show.presale_link, { :style => "color: #E5392B;" }

app/views/shows/edit.html.haml
=render partial: 'form'

app/views/shows/index.html.haml
%h1.center-text.monoton SHOWS AND DATES
-if @upcoming.any?
  =render partial: 'list', locals: {shows: @upcoming}
-else @upcoming
  .card
    .card-body
      %h5.center-text No new shows at this time. Please check back later.
-if @past.any?
  %h2.mx-4 Past Shows
  =render partial: 'list', locals: {shows: @past}
%br

app/views/shows/new.html.haml
=render partial: 'form'